export const PRICING_PLANS = {
        monthly: [
                {
                        tier: "Starter",
                        price: 149,
                        info: [
                                "750 Verified Leads/Month",
                                "7000+ Emails",
                                "375+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                        ],
                },
                {
                        tier: "Accelerate",
                        price: 299,
                        info: [
                                "3000 Verified Leads/Month",
                                "15000+ Emails",
                                "500+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                                "Premium Support",
                        ],
                },
                {
                        tier: "Supercharge",
                        price: 499,
                        info: [
                                "10,000 Verified Leads/Month",
                                "32,000+ Emails",
                                "3000+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                                "Premium Support",
                                "Accounts Manager",
                        ],
                },
        ],
        annually: [
                {
                        tier: "Starter",
                        originalPrice: 1788,
                        price: 1639,
                        info: [
                                "750 Verified Leads/Month",
                                "7000+ Emails",
                                "375+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                        ],
                },
                {
                        tier: "Accelerate",
                        originalPrice: 3588,
                        price: 3289,
                        info: [
                                "3000 Verified Leads/Month",
                                "15000+ Emails",
                                "500+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                                "Premium Support",
                        ],
                },
                {
                        tier: "Supercharge",
                        originalPrice: 5988,
                        price: 5489,
                        info: [
                                "10,000 Verified Leads/Month",
                                "32,000+ Emails",
                                "3000+ Lead Enrichment",
                        ],
                        features: [
                                "All core Maya Features",
                                "CRM Integration",
                                "Domain warm-up",
                                "Email warm-up",
                                "Unlimited mailboxes",
                                "Onboarding",
                                "Premium Support",
                                "Accounts Manager",
                        ],
                },
        ],
};
