// all the pricing plans for india and international + the features and information for each plan are defined here
export const PRICING_PLANS = {
  india: {
    monthly: [
      {
        tier: "Starter",
        price: "₹16000 + GST",
        info: [
          "750 Verified Leads/Month",
          "7000+ LLM Responses (Emails, Whatsapp, etc.)",
          "375+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
        ],
      },
      {
        tier: "Accelerate",
        price: "₹28000 + GST",
        info: [
          "3000 Verified Leads/Month",
          "15000+ LLM Responses (Emails, Whatsapp, etc.)",
          "500+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
        ],
      },
      {
        tier: "Supercharge",
        price: "₹52000 + GST",
        info: [
          "10,000 Verified Leads/Month",
          "32,000+ LLM Responses (Emails, Whatsapp, etc.)",
          "3000+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
          "Accounts Manager",
        ],
      },
    ],
    annually: [
      {
        tier: "Starter",
        originalPrice: "₹192000 + GST",
        price: "₹160000 + GST",
        info: [
          "750 Verified Leads/Month",
          "7000+ LLM Responses (Emails, Whatsapp, etc.)",
          "375+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
        ],
      },
      {
        tier: "Accelerate",
        originalPrice: "₹336000 + GST",
        price: "₹280000 + GST",
        info: [
          "3000 Verified Leads/Month",
          "15000+ LLM Responses (Emails, Whatsapp, etc.)",
          "500+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
        ],
      },
      {
        tier: "Supercharge",
        originalPrice: "₹624000 + GST",
        price: "₹520000 + GST",
        info: [
          "10,000 Verified Leads/Month",
          "32,000+ LLM Responses (Emails, Whatsapp, etc.)",
          "3000+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
          "Accounts Manager",
        ],
      },
    ],
  },
  international: {
    monthly: [
      {
        tier: "Starter",
        price: "$299",
        info: [
          "750 Verified Leads/Month",
          "7000+ LLM Responses (Emails, Whatsapp, etc.)",
          "375+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
        ],
      },
      {
        tier: "Accelerate",
        price: "$499",
        info: [
          "3000 Verified Leads/Month",
          "15000+ LLM Responses (Emails, Whatsapp, etc.)",
          "500+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
        ],
      },
      {
        tier: "Supercharge",
        price: "$899",
        info: [
          "10,000 Verified Leads/Month",
          "32,000+ LLM Responses (Emails, Whatsapp, etc.)",
          "3000+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
          "Accounts Manager",
        ],
      },
    ],
    annually: [
      {
        tier: "Starter",
        originalPrice: "$3588",
        price: "$2988",
        info: [
          "750 Verified Leads/Month",
          "7000+ LLM Responses (Emails, Whatsapp, etc.)",
          "375+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
        ],
      },
      {
        tier: "Accelerate",
        originalPrice: "$5988",
        price: "$4788",
        info: [
          "3000 Verified Leads/Month",
          "15000+ LLM Responses (Emails, Whatsapp, etc.)",
          "500+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
        ],
      },
      {
        tier: "Supercharge",
        originalPrice: "$10788",
        price: "$8388",
        info: [
          "10,000 Verified Leads/Month",
          "32,000+ LLM Responses (Emails, Whatsapp, etc.)",
          "3000+ Lead Enrichment",
        ],
        features: [
          "All core Maya Features",
          "CRM Integration",
          "Domain warm-up",
          "Email warm-up",
          "Unlimited mailboxes",
          "Onboarding",
          "Premium Support",
          "Accounts Manager",
        ],
      },
    ],
  },
};
