// all the pricing plans for india and international + the features and information for each plan are defined here
export const PRICING_PLANS = {
        india: {
                monthly: [
                        {
                                tier: "Starter",
                                price: 149,
                                info: [
                                        "750 Verified Leads/Month",
                                        "7000+ Emails",
                                        "375+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                ],
                        },
                        {
                                tier: "Accelerate",
                                price: 299,
                                info: [
                                        "3000 Verified Leads/Month",
                                        "15000+ Emails",
                                        "500+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                ],
                        },
                        {
                                tier: "Supercharge",
                                price: 599,
                                info: [
                                        "10,000 Verified Leads/Month",
                                        "32,000+ Emails",
                                        "3000+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                        "Accounts Manager",
                                ],
                        },
                ],
                annually: [
                        {
                                tier: "Starter",
                                originalPrice: 1788,
                                price: 1639,
                                info: [
                                        "750 Verified Leads/Month",
                                        "7000+ Emails",
                                        "375+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                ],
                        },
                        {
                                tier: "Accelerate",
                                originalPrice: 3588,
                                price: 3289,
                                info: [
                                        "3000 Verified Leads/Month",
                                        "15000+ Emails",
                                        "500+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                ],
                        },
                        {
                                tier: "Supercharge",
                                originalPrice: 5988,
                                price: 5489,
                                info: [
                                        "10,000 Verified Leads/Month",
                                        "32,000+ Emails",
                                        "3000+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                        "Accounts Manager",
                                ],
                        },
                ],
        },
        international: {
                monthly: [
                        {
                                tier: "Starter",
                                price: 399,
                                info: [
                                        "750 Verified Leads/Month",
                                        "7000+ Emails",
                                        "375+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                ],
                        },
                        {
                                tier: "Accelerate",
                                price: 799,
                                info: [
                                        "3000 Verified Leads/Month",
                                        "15000+ Emails",
                                        "500+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                ],
                        },
                        {
                                tier: "Supercharge",
                                price: 1599,
                                info: [
                                        "10,000 Verified Leads/Month",
                                        "32,000+ Emails",
                                        "3000+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                        "Accounts Manager",
                                ],
                        },
                ],
                annually: [
                        {
                                tier: "Starter",
                                originalPrice: 4788,
                                price: 4389,
                                info: [
                                        "750 Verified Leads/Month",
                                        "7000+ Emails",
                                        "375+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                ],
                        },
                        {
                                tier: "Accelerate",
                                originalPrice: 9588,
                                price: 8789,
                                info: [
                                        "3000 Verified Leads/Month",
                                        "15000+ Emails",
                                        "500+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                ],
                        },
                        {
                                tier: "Supercharge",
                                originalPrice: 19188,
                                price: 17589,
                                info: [
                                        "10,000 Verified Leads/Month",
                                        "32,000+ Emails",
                                        "3000+ Lead Enrichment",
                                ],
                                features: [
                                        "All core Maya Features",
                                        "CRM Integration",
                                        "Domain warm-up",
                                        "Email warm-up",
                                        "Unlimited mailboxes",
                                        "Onboarding",
                                        "Premium Support",
                                        "Accounts Manager",
                                ],
                        },
                ],
        },
};
